project: cockroachdb
topnav_title: CockroachDB
homepage_title: CockroachDB Docs
site_title: Cockroach Labs

url: "https://www.cockroachlabs.com"
baseurl: "/docs"

highlighter: rouge
markdown: kramdown

exclude: ["choose-a-deployment-profile.md", "recommended-environments.md", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
