project: cockroachdb
topnav_title: CockroachDB
homepage_title: CockroachDB Docs
site_title: Cockroach Labs
google_analytics: UA-63775601-1

baseurl: "/docs"
destination: ../cockroach_site

theme_file: theme-blue.css
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
