# project definitions
project: cockroachdb
audience: all
product: all
platform: all
version: all
destination: ../cockroachhtml
topnav_title: CockroachDB
homepage_title: CockroachDB
site_title: Cockroach Labs
google_analytics: 

# variables
sidebar_tagline: 
sidebar_version: 
project_file_name: doc

port: 4001

exclude:
  - doc_ymp*
  - configs/
  - _site
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: jesse@cockroachlabs.com
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true